### ISSUE TITLE
export default class

### ISSUE THREAD

**Issue by jareware** [researchgate/babel-plugin-react-class-display-name#1]
If you only have a single class in a file, it's convenient to export it during definition:

``` js
export default class ThreadListPanel extends React.Component {
  render() {}
}
```

Which will throw:

```
Error: /demo/app/ui/ThreadListPanel.js: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
    at NodePath.insertAfter (/demo/node_modules/babelify/node_modules/babel-core/lib/traversal/path/modification.js:150:13)
    at NodePath.ClassDeclaration (/demo/node_modules/babel-plugin-react-class-display-name/lib/index.js:15:26)
    at NodePath.call (/demo/node_modules/babelify/node_modules/babel-core/lib/traversal/path/context.js:56:28)
    at NodePath.visit (/demo/node_modules/babelify/node_modules/babel-core/lib/traversal/path/context.js:90:8)
    at TraversalContext.visitSingle (/demo/node_modules/babelify/node_modules/babel-core/lib/traversal/context.js:132:12)
    at TraversalContext.visit (/demo/node_modules/babelify/node_modules/babel-core/lib/traversal/context.js:148:19)
    at Function.traverse.node (/demo/node_modules/babelify/node_modules/babel-core/lib/traversal/index.js:76:17)
    at NodePath.visit (/demo/node_modules/babelify/node_modules/babel-core/lib/traversal/path/context.js:107:26)
    at TraversalContext.visitMultiple (/demo/node_modules/babelify/node_modules/babel-core/lib/traversal/context.js:108:16)
    at TraversalContext.visit (/demo/node_modules/babelify/node_modules/babel-core/lib/traversal/context.js:146:19)
```

**Comment by jareware** [comment]
Right, it's because the top level declaration (after which the `displayName` assignment should go) is then actually `ExportDefaultDeclaration`.

**Comment by danez** [comment]
Thanks.
